"""add car_number to standings_teams

Revision ID: 66e988c16941
Revises: 5bf87fc459ab
Create Date: 2026-04-28 04:45:53.959250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66e988c16941'
down_revision: Union[str, Sequence[str], None] = '5bf87fc459ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings_teams', sa.Column('car_number', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standings_teams', 'car_number')
    # ### end Alembic commands ###
