"""cars.number int to string for #007 style numbers

Revision ID: 6bba774a4c78
Revises: 71919c9a0b6b
Create Date: 2026-04-28 00:48:02.394856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bba774a4c78'
down_revision: Union[str, Sequence[str], None] = '71919c9a0b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False,
               postgresql_using='number::text')


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('cars', 'number',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='number::integer')
    # ### end Alembic commands ###
