"""add race_class_id to standings

Revision ID: 71919c9a0b6b
Revises: a0e027ebc22d
Create Date: 2026-04-27 22:38:55.017855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71919c9a0b6b'
down_revision: Union[str, Sequence[str], None] = 'a0e027ebc22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standings_drivers', sa.Column('race_class_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_standings_drivers_race_class_id'), 'standings_drivers', ['race_class_id'], unique=False)
    op.create_foreign_key(None, 'standings_drivers', 'race_classes', ['race_class_id'], ['id'])
    op.add_column('standings_manufacturers', sa.Column('race_class_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_standings_manufacturers_race_class_id'), 'standings_manufacturers', ['race_class_id'], unique=False)
    op.create_foreign_key(None, 'standings_manufacturers', 'race_classes', ['race_class_id'], ['id'])
    op.add_column('standings_teams', sa.Column('race_class_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_standings_teams_race_class_id'), 'standings_teams', ['race_class_id'], unique=False)
    op.create_foreign_key(None, 'standings_teams', 'race_classes', ['race_class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'standings_teams', type_='foreignkey')
    op.drop_index(op.f('ix_standings_teams_race_class_id'), table_name='standings_teams')
    op.drop_column('standings_teams', 'race_class_id')
    op.drop_constraint(None, 'standings_manufacturers', type_='foreignkey')
    op.drop_index(op.f('ix_standings_manufacturers_race_class_id'), table_name='standings_manufacturers')
    op.drop_column('standings_manufacturers', 'race_class_id')
    op.drop_constraint(None, 'standings_drivers', type_='foreignkey')
    op.drop_index(op.f('ix_standings_drivers_race_class_id'), table_name='standings_drivers')
    op.drop_column('standings_drivers', 'race_class_id')
    # ### end Alembic commands ###
