"""add logo_url to manufacturers

Revision ID: 813531c47568
Revises: 66e988c16941
Create Date: 2026-04-28 05:23:24.610069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813531c47568'
down_revision: Union[str, Sequence[str], None] = '66e988c16941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturers', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufacturers', 'logo_url')
    # ### end Alembic commands ###
