"""add rounds to car_drivers

Revision ID: c0d299ffa884
Revises: 6bba774a4c78
Create Date: 2026-04-28 04:15:29.543689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d299ffa884'
down_revision: Union[str, Sequence[str], None] = '6bba774a4c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_drivers', sa.Column('rounds', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car_drivers', 'rounds')
    # ### end Alembic commands ###
